<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tw_coderdojo"
 *
 * Auto generated by Extension Builder 2015-11-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'CoderDojo Nürnberg',
	'description' => 'Plugins for the CoderDojo Nürnberg website',
	'category' => 'plugin',
	'author' => 'Joschi Kuphal',
	'author_email' => 'joschi@tollwerk.de',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.5.0-7.6.99',
			'static_info_tables' => '6.3.4-',
			'tw_webperf' => '0.1.0-',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);